[package]
edition = "2024"
name = "qobuz-downloader"
version = "0.1.0"

[dependencies]
async-channel = { version = "2.5.0", default-features = false, features = [
    "std",
] }
libadwaita = { version = "0.9.2", features = [
    "gio_v2_80",
    "gtk_v4_24",
    "v1_10",
] }
num-traits = { version = "0.2.19", default-features = false }
oo7 = { version = "0.6.0", default-features = false, features = [
    "openssl_crypto",
    "tokio",
] }
parking_lot = { version = "0.12.5", default-features = false }
qobuz-api = { version = "2.0.0", default-features = false }
regex = { version = "1.13.1", default-features = false }
reqwest = { version = "0.13.5", default-features = false }
serde = { version = "1.0.229", default-features = false }
serde_json = { version = "1.0.151", default-features = false }
thiserror = { version = "2.0.20", default-features = false }
tokio = { version = "1.53.1", default-features = false }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false, features = [
    "ansi",
] }

[lints.rust]
ambiguous_negative_literals = "deny"
closure_returning_async_block = "deny"
dead_code_pub_in_binary = "deny"
deprecated_in_future = "deny"
deprecated_safe = { level = "deny", priority = -1 }
deref_into_dyn_supertrait = "deny"
ffi_unwind_calls = "deny"
future_incompatible = { level = "deny", priority = -1 }
impl_trait_redundant_captures = "deny"
keyword_idents = { level = "deny", priority = -1 }
let_underscore = { level = "deny", priority = -1 }
linker_info = "deny"
macro_use_extern_crate = "deny"
meta_variable_misuse = "deny"
missing_copy_implementations = "deny"
missing_debug_implementations = "deny"
missing_docs = "deny"
non_ascii_idents = "deny"
nonstandard_style = { level = "deny", priority = -1 }
raw_borrows_via_references = "deny"
redundant_imports = "deny"
redundant_lifetimes = "deny"
refining_impl_trait = { level = "deny", priority = -1 }
rust_2018_compatibility = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "deny", priority = -1 }
rust_2021_compatibility = { level = "deny", priority = -1 }
rust_2024_compatibility = { level = "deny", priority = -1 }
single_use_lifetimes = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unit_bindings = "deny"
unknown_or_malformed_diagnostic_attributes = { level = "deny", priority = -1 }
unnameable_types = "deny"
unreachable_pub = "deny"
unsafe_code = "deny"
unstable_features = "deny"
unused = { level = "deny", priority = -1 }
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
unused_results = "deny"
variant_size_differences = "deny"
warnings = { level = "deny", priority = -1 }

[lints.clippy]
# unused_trait_names = "deny"
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
arbitrary_source_item_ordering = "deny"
arithmetic_side_effects = "deny"
as_conversions = "deny"
as_pointer_underscore = "deny"
as_underscore = "deny"
assertions_on_result_states = "deny"
await_holding_lock = "deny"
await_holding_refcell_ref = "deny"
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_sign_loss = "deny"
clone_on_ref_ptr = "deny"
dbg_macro = "deny"
debug_assert_with_mut_call = "deny"
doc_paragraphs_missing_punctuation = "deny"
else_if_without_else = "deny"
empty_drop = "deny"
empty_enum_variants_with_brackets = "deny"
error_impl_error = "deny"
exit = "deny"
expect_used = "deny"
expl_impl_clone_on_copy = "deny"
float_cmp = "deny"
float_cmp_const = "deny"
fn_to_numeric_cast_any = "deny"
get_unwrap = "deny"
if_let_mutex = "deny"
if_then_some_else_none = "deny"
indexing_slicing = "deny"
infallible_try_from = "deny"
invalid_upcast_comparisons = "deny"
iter_not_returning_iterator = "deny"
large_futures = "deny"
let_underscore_future = "deny"
let_underscore_must_use = "deny"
let_underscore_untyped = "deny"
lossy_float_literal = "deny"
map_err_ignore = "deny"
map_with_unused_argument_over_ranges = "deny"
mem_forget = "deny"
missing_assert_message = "deny"
missing_asserts_for_indexing = "deny"
missing_docs_in_private_items = "deny"
missing_trait_methods = "deny"
mod_module_files = "deny"
multiple_unsafe_ops_per_block = "deny"
mutex_atomic = "deny"
mutex_integer = "deny"
needless_raw_strings = "deny"
negative_feature_names = "deny"
nursery = { level = "deny", priority = -1 }
panic = "deny"
panic_in_result_fn = "deny"
pedantic = { level = "deny", priority = -1 }
print_stderr = "deny"
print_stdout = "deny"
pub_use = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
redundant_feature_names = "deny"
redundant_test_prefix = "deny"
redundant_type_annotations = "deny"
ref_patterns = "deny"
rest_pat_in_fully_bound_structs = "deny"
return_and_then = "deny"
same_name_method = "deny"
string_lit_chars_any = "deny"
string_slice = "deny"
tests_outside_test_module = "deny"
todo = "deny"
try_err = "deny"
unchecked_time_subtraction = "deny"
undocumented_unsafe_blocks = "deny"
unimplemented = "deny"
unnecessary_safety_comment = "deny"
unnecessary_safety_doc = "deny"
unreachable = "deny"
unused_result_ok = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"
